### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by levinsonmm** [levinsonmm/MI-449-SS17-741-html-semantic-elements-5BSgA-#1]
@stuartpearman Can you take a look at this? It's [hosted here](https://levinsonmm.github.io/MI-449-SS17-741-html-semantic-elements-5BSgA-/) and meets the following criteria:

- [x] Place a `nav` element at the top of the page that includes (fake) links to other pages
- [x] Use the `main` element appropriately
- [x] Include three products your store sells, all listed on the same Products page
- [x] For each product, correctly use an `article`, `header`, and `footer` element
- [x] Use `figure` and `figcaption` to show what each product looks like
- [x] Each product includes a `nav` element with one or more links to related products (the links don't have to go anywhere)
- [x] Use an `aside` in one or more products to advertise a promotion or discount for that product

**Comment by stuartpearman** [comment]
Awesome job Madeline 🌞  The only thing you might change is either putting the `h1` in the `main` tag, or wrapping the `h1` and top `nav` in a `header` tag. Since the `h1` describes the entire store and not just the current page, I would probably group it in the `header` though.

You seem to have a pretty good grasp of this, but to elaborate a bit, a `header` generally holds content at the top and is not directly related to the `main` content. It's nice to group things together in some way so that there are no lonely content tags floating around in the site. It helps other coders make sense of the structure of a page, and it helps screen readers and assistive devices do their jobs more easily 🤖 

Let me know if you have any questions, and when you're done just comment back :+1:

**Comment by levinsonmm** [comment]
As recommended, I put the nav and h1 in a header! Let me know if I need to do anything else!

**Comment by stuartpearman** [comment]
Looks great Madeline! 🙂  :shipit:
